### ISSUE TITLE
kotlin 1.6.0 빌드 오류

### ISSUE THREAD

**Issue by kim-uno** [iamport/iamport-android#47]
kotlin 1.6.0 버전에서 `Iamport.create(this)` 호출시 발생하는 에러 전문 첨부합니다.
iamport 1.2.0 입니다.

```kotlin
java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:109)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:106)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin(Iamport.kt:106)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin$default(Iamport.kt:101)
        at com.iamport.sdk.domain.core.Iamport.create(Iamport.kt:94)
```

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

현재 SDK 에서 사용중인 lib(koin) 에서 kotlin 1.6.0 에 대한 이슈가 있습니다.
https://github.com/InsertKoinIO/koin/issues/1188

저희 내부에선 아래 정도를 고려하고 있습니다.
- 추후 이슈가 수정된 koin 버전을 반영
- koin 자체를 걷어냄
- 다른 DI lIb 의 사용(dagger-hilt 등)

단, 어느 것을 택하더라도 개발 및 배포까지 시간이 소요될 것 같습니다.
그 전까지는 kotlin 1.5.x 버전을 이용해주시기 바랍니다.

감사합니다.

**Comment by kjh5833** [comment]
이슈 리포팅에 감사드리며, 
해결이 될 때까지 open 하도록 하겠습니다.

**Comment by chanjungkim** [comment]
개인적으로 왠지 다 걷어내면 좋을 거 같네요.

**Comment by chanjungkim** [comment]
1.5.30도 안 되어서
1.5.21로 내리니까 되네요.

**Comment by kjh5833** [comment]
아임포트 기술지원팀입니다.

- iamport-android v1.3.0 에서 koin 에러 회피 방안이 적용되어 kotlin 1.6.0 을 사용할 수 있습니다.
- [koin 3.2.0 에서 해당 이슈가 해결](https://github.com/InsertKoinIO/koin/issues/1188#issuecomment-1011218036) 될거라고 하는데,
이 부분은 3.2.0이 배포되면 내부에서 충분한 테스트 후 iamport-android 다음 버전에서 반영 예정입니다.

- 이와 별도로 koin 을 걷어내는 작업은 계속 진행중에 있습니다.

v1.3.0 사용시에도 문제가 있으시면 이슈 열어주시기 바랍니다.
감사합니다.
