### ISSUE TITLE
jdk 11에서 코인 이슈

### ISSUE THREAD

**Issue by jklee103** [iamport/iamport-android#52]
targetSdk 31 -> jdk 11 -> 31 api 기기에서는 잘 실행되나, android 30 기기에서 빌드 후 코인 에러가 납니다. 
코틀린 버전은 아직 1.5.x 입니다. 아임포트 라이브러리 또한 최신버전입니다.

```
java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/.../base.apk!classes3.dex)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:109)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:106)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin(Iamport.kt:106)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin$default(Iamport.kt:101)
        at com.iamport.sdk.domain.core.Iamport.create(Iamport.kt:94)
```

**Comment by kjh5833** [comment]
https://github.com/iamport/iamport-android/issues/47 와 같은 이슈로 보입니다.
targetSdk 31 빌드를 30 디바이스에서 실행시 문제가 발생한다는 말씀이신가요?
정확한 코틀린 버전이 어떻게 될까요?

**Comment by kjh5833** [comment]
example 앱 내부 테스트에선 재현되지 않았습니다.
`check/customer` 브랜치의 example 앱 동작 확인 부탁드립니다.

```
iamport-android : 1.2.0
kotlin : 1.5.30
targetSdkVersion : 31
```

**Comment by jklee103** [comment]
코틀린버전은 1.5.10 이고, ` check/customer` 브랜치에 현재 프로젝트와 같은 버전으로 실행시키면 잘 작동하나 제 프로젝트에서는 다시 롤백시키고 처음부터 작업해봐도 같은 에러가 발생하네요..

**Comment by kjh5833** [comment]
`check/customer` 브랜치를 고객님의 환경에 맞춰 실행시 31, 30 디바이스 모두 정상동작이라는 말씀이실까요?

혹시 koin 을 따로 사용중이신가요?

**Comment by kjh5833** [comment]
진행사항이 없어 이슈 닫도록 하겠습니다 문제 재현시 이슈 재오픈 하시거나,
아래 메일로 문의 부탁드립니다.
https://faq.iamport.kr/e8b60dea-490b-40a2-9ce7-d3f75a114eae
